name: Version and Changelog Update

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  version_and_changelog:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install standard-version
      run: npm install -g standard-version
    
    - name: Configure Git
      run: |
        git config --global user.name 'JhonDevS'
        git config --global user.email 'sierrazuluaga.j@gmail.com'
    
    - name: Generate Version and Changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        standard-version
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push --follow-tags origin main