name: Version and Changelog Update

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  version_and_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install standard-version
      run: npm install -g standard-version
    
    - name: Configure Git
      uses: actions/git-actions@v0.3.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.actor }}
        email: ${{ github.actor }}@users.noreply.github.com
    
    - name: Generate Version and Changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        standard-version
        git push --follow-tags origin main